import os
from datetime import datetime

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage

from app.paths import REPORTS_DIR

STATUS_RGB = {
    "pass": RGBColor(0x16, 0x65, 0x34),
    "violation": RGBColor(0xDC, 0x26, 0x26),
    "needs_review": RGBColor(0xD9, 0x77, 0x06),
}


def generate_compliance_pdf(scan, violations: list) -> str:
    filename = f"compliance_report_scan_{scan.id}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=18)
    story = []

    story.append(Paragraph("Legal Metrology Compliance Report", title_style))
    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011", styles["Normal"]))
    story.append(Spacer(1, 8))

    status_color = {"pass": colors.green, "violation": colors.red, "needs_review": colors.orange}.get(scan.status, colors.black)
    status_style = ParagraphStyle("Status", parent=styles["Heading2"], textColor=status_color)
    story.append(Paragraph(f"Result: {scan.status.upper().replace('_', ' ')}", status_style))
    story.append(Spacer(1, 4))

    meta_rows = [
        ["Scan ID", str(scan.id)],
        ["Product", scan.product_name or "—"],
        ["Category", scan.category or "—"],
        ["Rule version applied", scan.rule_version],
        ["Compliance score", f"{(scan.compliance_score or 0) * 100:.0f}%"],
        ["Scanned at", scan.created_at.strftime("%d %b %Y, %H:%M") if scan.created_at else "—"],
        ["Report generated", datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")],
    ]
    meta_table = Table(meta_rows, colWidths=[150, 320])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 12))

    if scan.processed_image_path and os.path.exists(scan.processed_image_path):
        try:
            story.append(RLImage(scan.processed_image_path, width=140 * mm, height=100 * mm, kind="proportional"))
            story.append(Spacer(1, 12))
        except Exception:
            pass

    if violations:
        story.append(Paragraph("Violations & Flags", styles["Heading2"]))
        data = [["Field", "Issue", "Rule Ref.", "Severity", "Detail"]]
        for v in violations:
            data.append([
                v["label"],
                v["issue_type"].replace("_", " ").title(),
                v["rule_ref"],
                v["severity"].title(),
                v["detail"],
            ])
        vtable = Table(data, colWidths=[80, 65, 65, 45, 190])
        vtable.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ]))
        story.append(vtable)
    else:
        story.append(Paragraph("No violations detected. All mandatory declarations checked were present and well-formed.", styles["Normal"]))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "This report is generated by an automated first-pass scanning system and is intended to assist, "
        "not replace, an enforcement officer's judgement. Low-confidence extractions should be manually verified.",
        styles["Italic"],
    ))

    doc.build(story)
    return filepath


def generate_compliance_docx(scan, violations: list) -> str:
    """Editable counterpart to the PDF report — same content, as a .docx an
    officer can annotate, correct, or append findings to before filing."""
    filename = f"compliance_report_scan_{scan.id}.docx"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = Document()

    doc.add_heading("Legal Metrology Compliance Report", level=1)
    doc.add_paragraph("Legal Metrology (Packaged Commodities) Rules, 2011")

    status_para = doc.add_paragraph()
    status_run = status_para.add_run(f"Result: {scan.status.upper().replace('_', ' ')}")
    status_run.bold = True
    status_run.font.size = Pt(14)
    status_run.font.color.rgb = STATUS_RGB.get(scan.status, RGBColor(0, 0, 0))

    meta_table = doc.add_table(rows=0, cols=2)
    meta_table.style = "Light Grid Accent 1"
    meta_rows = [
        ("Scan ID", str(scan.id)),
        ("Product", scan.product_name or "—"),
        ("Category", scan.category or "—"),
        ("Rule version applied", scan.rule_version),
        ("Compliance score", f"{(scan.compliance_score or 0) * 100:.0f}%"),
        ("Font-size check", "Performed" if scan.font_check_status == "checked" else "Skipped (no calibration)"),
        ("Scanned at", scan.created_at.strftime("%d %b %Y, %H:%M") if scan.created_at else "—"),
        ("Report generated", datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")),
    ]
    for label, value in meta_rows:
        row = meta_table.add_row()
        row.cells[0].text = label
        row.cells[1].text = value

    doc.add_paragraph()

    if scan.processed_image_path and os.path.exists(scan.processed_image_path):
        try:
            doc.add_picture(scan.processed_image_path, width=Inches(5))
        except Exception:
            pass

    if violations:
        doc.add_heading("Violations & Flags", level=2)
        vtable = doc.add_table(rows=1, cols=4)
        vtable.style = "Light Grid Accent 1"
        hdr = vtable.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "Field", "Rule Ref.", "Severity", "Detail"
        for v in violations:
            row = vtable.add_row().cells
            row[0].text = v["label"]
            row[1].text = v["rule_ref"]
            row[2].text = v["severity"].title()
            row[3].text = v["detail"]
    else:
        doc.add_paragraph("No violations detected. All mandatory declarations checked were present and well-formed.")

    doc.add_paragraph()
    note = doc.add_paragraph()
    note_run = note.add_run(
        "This report is generated by an automated first-pass scanning system and is intended to assist, "
        "not replace, an enforcement officer's judgement. Low-confidence extractions should be manually verified."
    )
    note_run.italic = True

    doc.save(filepath)
    return filepath
